apiVersion: v1

kind: Service

metadata:
  name: usermanager-service
  namespace: dev-usermanager

spec:
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8002
      targetPort: 6002
  selector:
    app: usermanager-app
