apiVersion: v1

kind: Service

metadata:
  name: bitcoin-service
  namespace: dev-bitcoin

spec:
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8001
      targetPort: 6001
  selector:
    app: bitcoin-app
